######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
# logo_on_white: "https://www.mitjaa.org/wp-content/uploads/2024/01/final-768x856.png"
# logo_on_black: "https://www.mitjaa.org/wp-content/uploads/2024/01/final-768x856.png"
logo_on_white: "/work-in-progress-circle-2.png"
logo_on_black: "/work-in-progress-circle-2.png"
custom_js: ["js/header-scroll.js"]
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/work-in-progress-circle-2.png"]

# github:
#   repo_url: "https://github.com/username/repo/blob/master"
#   show_edit_link: false

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: ""
  instagram: ""
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: "https://x.com/jaa_mit_post"
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
